name: Idiom Comic Submission

description: Submit your comic

title: "[Comic] "

labels:
  - submission

body:

  - type: input
    id: student
    attributes:
      label: Student Name
    validations:
      required: true

  - type: input
    id: idiom
    attributes:
      label: Idiom Used
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Comic Website URL
    validations:
      required: true

  - type: textarea
    id: explanation
    attributes:
      label: Meaning of the Idiom
